### PR TITLE
Update CC amplitude loading

### PR DESCRIPTION
**Pull request by jarrodmcc**
Makes the CCSD amplitude loading consistent with new molecular data structure in FermiLib

### CODE REVIEW

**Comment by jarrodmcc** [comment]
Oops I forgot to start from a clean branch so there are some excess commits in there. Shouldn't be a problem after squashing, only two lines of real changes.

**Review by damiansteiger — APPROVED** [review]
👍

**Comment by babbush** [comment]
Hmm, Damian you might want to unmerge that. That PR will break this code until Jarrod's other PR on FermiLib is accepted. The problem is that Jarrod's other PR decreases test coverage so we are waiting until he gets it up to accept this one. I would have blocked the PR but I actually don't know how to do this.

**Comment by damiansteiger** [comment]
You can block PR in two ways:
1) Leave a comment saying that you wait for pull request X on FermiLib
2) Assign yourself as a reviewer (and maybe also leave a comment)

I guess it shouldn't take Jarrod too long to increase that test coverage. Unless he is waiting for more than a week, I would leave the pull request as the main focus should be on having all master branches in sync... But if you like, click revert and it will undo the merge.

**Pull request merged**
